/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as VocabularyUnlearnedRouteImport } from './routes/vocabulary_.unlearned'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsRoute,
} as any)
const VocabularyUnlearnedRoute = VocabularyUnlearnedRouteImport.update({
  id: '/vocabulary_/unlearned',
  path: '/vocabulary/unlearned',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/homework': typeof HomeworkRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/mistakes': typeof MistakesRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/vocabulary/unlearned': typeof VocabularyUnlearnedRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/homework': typeof HomeworkRoute
  '/mistakes': typeof MistakesRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/vocabulary/unlearned': typeof VocabularyUnlearnedRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/homework': typeof HomeworkRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/mistakes': typeof MistakesRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/vocabulary_/unlearned': typeof VocabularyUnlearnedRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grammar'
    | '/homework'
    | '/lessons'
    | '/mistakes'
    | '/review'
    | '/vocabulary'
    | '/lessons/$lessonId'
    | '/vocabulary/unlearned'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grammar'
    | '/homework'
    | '/mistakes'
    | '/review'
    | '/vocabulary'
    | '/lessons/$lessonId'
    | '/vocabulary/unlearned'
    | '/lessons'
  id:
    | '__root__'
    | '/'
    | '/grammar'
    | '/homework'
    | '/lessons'
    | '/mistakes'
    | '/review'
    | '/vocabulary'
    | '/lessons/$lessonId'
    | '/vocabulary_/unlearned'
    | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrammarRoute: typeof GrammarRoute
  HomeworkRoute: typeof HomeworkRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  MistakesRoute: typeof MistakesRoute
  ReviewRoute: typeof ReviewRoute
  VocabularyRoute: typeof VocabularyRoute
  VocabularyUnlearnedRoute: typeof VocabularyUnlearnedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/vocabulary_/unlearned': {
      id: '/vocabulary_/unlearned'
      path: '/vocabulary/unlearned'
      fullPath: '/vocabulary/unlearned'
      preLoaderRoute: typeof VocabularyUnlearnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrammarRoute: GrammarRoute,
  HomeworkRoute: HomeworkRoute,
  LessonsRoute: LessonsRouteWithChildren,
  MistakesRoute: MistakesRoute,
  ReviewRoute: ReviewRoute,
  VocabularyRoute: VocabularyRoute,
  VocabularyUnlearnedRoute: VocabularyUnlearnedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
